import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createServer} from 'node:http';import {createHash} from 'node:crypto';import {spawn} from 'node:child_process';import assert from 'node:assert/strict';
const {chromium}=await import('file:///C:/Users/chorr/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const here=path.dirname(fileURLToPath(import.meta.url)),out=path.resolve(here,'../evidence/pre-alpha-reel'),qa=path.join(out,'decoded');await fs.mkdir(qa,{recursive:true});
const server=createServer(async(req,res)=>{try{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1),p=path.resolve(out,name);if(!p.startsWith(out+path.sep))throw Error('outside');res.setHeader('Content-Type',name.endsWith('.webm')?'video/webm':name.endsWith('.png')?'image/png':'text/html');res.end(await fs.readFile(p));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{
 browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const page=await browser.newPage({viewport:{width:1920,height:1080}});await page.goto('http://127.0.0.1:'+server.address().port+'/watch.html');await page.waitForFunction(()=>document.querySelector('video').readyState>=2);
 const metadata=await page.evaluate(()=>{const v=document.querySelector('video');return {duration:v.duration,width:v.videoWidth,height:v.videoHeight,codecSupported:v.canPlayType('video/webm; codecs="vp8"')};});assert.equal(metadata.duration,38);assert.equal(metadata.width,1920);assert.equal(metadata.height,1080);
 const times=[...new Set([...Array.from({length:38},(_,i)=>i),3.2,3.4,3.6,3.8,4.2,5.7,7.2,8.8,9.6,10.6,13.6,14.5,17.9,21.4,25.13,25.27,25.4,27.4,27.8,28.13,28.3,28.7,29.37,30.4,30.9,31.4,32.6,33.4,34.3])].sort((a,b)=>a-b),frames=[];
 // Decode with the independent VP8 decoder. Browser seeked alone is insufficient
 // evidence of a new decoded frame (particularly on servers without byte ranges).
 for(let i=0;i<times.length;i+=4){const batch=await Promise.allSettled(times.slice(i,i+4).map(async t=>{
  const name='frame-'+t.toFixed(2).replace('.','-')+'.png';await new Promise((resolve,reject)=>{const child=spawn('C:/Users/chorr/AppData/Local/ms-playwright/ffmpeg-1011/ffmpeg-win64.exe',['-v','error','-y','-ss',String(t),'-i',path.join(out,'pre-alpha-reel.webm'),'-frames:v','1','-c:v','png','-update','1',path.join(qa,name)],{windowsHide:true,stdio:['ignore','ignore','pipe']});let error='';child.stderr.on('data',d=>error+=d);child.on('error',reject);child.on('close',code=>code===0?resolve():reject(Error(error)));});return {time:t,file:'decoded/'+name};
 }));for(const r of batch){if(r.status==='rejected')throw r.reason;frames.push(r.value);}}
 const result={...metadata,frameCountEncoded:1140,sha256:createHash('sha256').update(await fs.readFile(path.join(out,'pre-alpha-reel.webm'))).digest('hex'),decodedSamples:frames};await fs.writeFile(path.join(out,'decoded-audit.json'),JSON.stringify(result,null,2)+'\n');
 const sheets=[['overview',frames.filter(f=>Number.isInteger(f.time))],['motion',frames.filter(f=>!Number.isInteger(f.time))]];
 for(const [name,rows]of sheets){await page.setContent('<style>body{margin:0;background:#181611;color:#fff;font:20px Georgia}main{display:grid;grid-template-columns:repeat(3,640px)}figure{margin:0}img{display:block;width:640px;height:360px}figcaption{height:30px;padding-left:12px}</style><main>'+rows.map(f=>'<figure><img src="http://127.0.0.1:'+server.address().port+'/'+f.file+'"><figcaption>'+f.time.toFixed(2)+' seconds</figcaption></figure>').join('')+'</main>');await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth));await page.screenshot({path:path.join(qa,name+'.png'),fullPage:true});}
 console.log(JSON.stringify({metadata,decodedSamples:frames.length,sha256:result.sha256}));
}finally{await browser?.close();await new Promise(r=>server.close(r));}
