import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createServer} from 'node:http';import assert from 'node:assert/strict';
import {faceFor,DIRS} from '../../src/tactical/hex.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright'),here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..'),out=path.join(here,'evidence/revision-11');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.glb':'model/gltf-binary'};
const server=createServer(async(req,res)=>{try{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep))throw Error('outside');res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(await fs.readFile(file));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({headless:true,...(process.env.PROTOTYPE_BROWSER?{executablePath:process.env.PROTOTYPE_BROWSER}:{})});const page=await browser.newPage({viewport:{width:1600,height:1080}}),errors=[],headings=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/arena/prototype-3d/index.html`);await page.waitForFunction(()=>window.tabletopPrototype?.ready);
 const orientation=await page.evaluate(async()=>{const T=await import('three'),{classRim}=await import('./rim-labels.js'),{baseGeometry}=await import('./stands.js'),rim=classRim('KFG-01'),base=baseGeometry(),result=[];
  for(let heading=0;heading<6;heading++){const m=new T.Matrix4().makeRotationY(heading*Math.PI/3);result.push({heading,bow:new T.Vector3(1,0,0).transformDirection(m).toArray(),triangle:new T.Vector3(...base.userData.facingTriangle.bow).transformDirection(m).toArray(),faces:rim.geometry.userData.rim.faces.map(f=>({face:f.face,normal:new T.Vector3(f.normal.x,0,f.normal.z).normalize().transformDirection(m).toArray()}))});}return result;});
 for(const r of orientation){assert.deepEqual(r.triangle,r.bow);assert.deepEqual(r.faces.map(f=>f.face).sort(),[2,4,6]);for(const f of r.faces){const dir=DIRS.findIndex(d=>{const x=Math.sqrt(3)*(d.q+d.r/2),z=1.5*d.r,l=Math.hypot(x,z);return Math.hypot(x/l-f.normal[0],z/l-f.normal[2])<1e-6;});assert.notEqual(dir,-1);assert.equal(faceFor(r.heading,dir),f.face);if(f.face===2)assert.ok(Math.hypot(f.normal[0]-r.bow[0],f.normal[2]-r.bow[2])<1e-6);}}
 for(let h=0;h<6;h++){const r=await page.evaluate(h=>window.tabletopPrototype.reviewHeading(h),h);headings.push(r);await page.locator('.frame').screenshot({path:path.join(out,'heading-'+h+'.png')});}
 assert.deepEqual(errors,[]);await fs.writeFile(path.join(out,'facing.json'),JSON.stringify({orientation,headings,errors},null,2)+'\n');
 console.log(JSON.stringify(headings.map(h=>({heading:h.heading,triangles:h.triangles.map(t=>({id:t.id,bounds:t.bounds,visible:t.unoccludedFraction,changed:t.changedBufferPixelsAbove002,contrast:t.maxLinearDelta})),rimCaps:h.rim.units.map(u=>({id:u.id,best:u.best.capPixels/h.triangles[0].bufferPixelsPerCssPixel}))})),null,2));
}finally{await browser?.close();await new Promise(r=>server.close(r));}
