import {weaponSpecification, systemsSpecification} from './specifications.js';
import {escapeHTML as esc, format, FACE_NAMES} from '../arena/command-model.js';
import {arcLabel} from '../arena/arc-labels.js';
const n=format,sign=v=>v>=0?`+${n(v)}`:n(v);
const field=(label,value)=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`;

export function weaponDossier(w,{compact=false}={}) {
  if(!w)return '<p class="footnote">No weapon selected. Choose an installed mount or a catalogue definition.</p>';
  const s=w.spec;
  const power=s.kind==='beam'?`Up to ${n(w.power)} P / shot`:`${n(w.power)} P / ${s.kind==='missile'?'launch':'discharge'}`;
  const ammo=w.magazine===null?'No ammunition consumed':`${n(w.magazine)} shared / 1 per launch`;
  return `<div class="dossier-title"><span class="eyebrow">${w.installation?'INSTALLED WEAPON':'CATALOGUE PREVIEW / NOT INSTALLED'}</span><h3>${esc(w.name)}</h3><small>${esc(w.key)}</small></div><dl class="spec-grid">${field('Class / family',w.family)}${field('Range on this hull',`${n(w.maxRange)} hex`)}${field('Power demand',power)}${field('Magazine',ammo)}${field('Firing / reload pace',w.cadence)}${field('Physical size',w.size)}</dl>
    <p class="spec-note">${s.kind==='spinal'?`Bank ${n(w.charge.required)} P · draw up to ${n(w.charge.draw)} P/turn · ready hold up to ${n(w.charge.hold)} P/turn · cooldown setting ${n(w.charge.cooldown)} turns.`:`One turn = ${w.actionsPerTurn} actions. A mount used in any action resets next turn, not next action.`}${s.kind==='missile'?' All launchers share the hull magazine. No ammunition refill during battle.':' No ammunition reload is needed.'}</p>
    ${compact?'':`<p class="spec-note">Base range ${n(w.baseRange)} × hull reach ${n(w.reach)} → ${n(w.maxRange)} hex (rounded per endpoint). ${s.kind==='beam'?'Beam damage on a hit is allocated power + band bonus; limited power can produce a weaker shot.':s.kind==='missile'?`Base warhead ${n(s.damage)} damage + band modifier, floored at zero; impact may be intercepted.`:`Base bolt ${n(s.damage)} damage + band bonus; ${s.bypassShield?'bypasses shields':'shields apply normally'}.`}</p>
    <div class="spec-table-wrap" tabindex="0" role="region" aria-label="Weapon range bands"><table class="spec-bands"><thead><tr><th>Base / hex</th><th>On this hull / hex</th><th>Damage ${s.kind==='missile'?'modifier':'bonus'}</th><th>Band accuracy</th></tr></thead><tbody>${w.bands.map(b=>`<tr><td>${b.baseFrom}–${b.baseTo}</td><td>${b.collapsed?'No distinct range after rounding':`${b.from}–${b.to}`}</td><td>${sign(s.kind==='missile'?b.damageMod:b.damageBonus)}</td><td>${s.kind==='missile'?'Not a beam hit roll':sign(b.toHitMod)}</td></tr>`).join('')}</tbody></table></div>
    ${w.charge?`<p class="spec-note">${w.charge.minimumTicks===null?'Zero charging draw: this bank cannot charge from empty.':`At least ${w.charge.minimumTicks} charging turn(s) from empty at the full definition draw.`} ${w.charge.startRange===null?'No charge-start distance gate.':`A cold bank waits for an enemy within ${n(w.charge.startRange)} hex; this gate is not scaled by hull reach.`} Power shortage can delay charging; readiness does not promise a shot. ${w.charge.planted?'Charging/ready helm is planted once the bank is active.':''} Cooldown is checked at turn start; reaching zero reconnects the bank, and drawing resumes on the following turn. Target policy can hold a ready shot.</p>`:''}`}`;
}

export function renderSpecificationPanel({pack,tuning,reading,selected}) {
  const w=weaponSpecification(pack,tuning,{mountId:selected}),s=systemsSpecification(pack,reading),f=reading.forecast;
  const $=id=>document.getElementById(id);
  $('weapon-specification').innerHTML=weaponDossier(w,{compact:true});
  $('spec-design').textContent=`${pack.design.name} · ${pack.design.faction} / ${pack.design.className} · r${pack.design.revision}`;
  $('power-relationship').textContent=`Reactors + impulse → one shared pool → movement / weapons / systems → ${n(s.remaining)} P remaining for shields. Reserve is a spending floor, not another pool.`;
  $('spec-power-map').innerHTML=`<section class="power-node supply"><h3>01 / GENERATE</h3><strong>${n(s.full)} <small>P / turn</small></strong><p>${s.reactors.map(r=>`${esc(r.name)} ${n(r.power)} P`).join(' + ')} + impulse ${n(s.impulse)} P</p><p>Supply is refilled from surviving sources each turn.</p></section>
    <section class="power-node allocation"><h3>02 / SHARED BUS</h3><strong>${n(s.available)} <small>P after upkeep</small></strong><p>${n(s.overhead)} P start-turn upkeep / spinal charge.</p><p><b>${n(s.reserve)} P reserved</b> within this pool. Held back from ordinary spending, not consumed or added.</p></section>
    <section class="power-node demand"><h3>03 / FORECAST DRAWS</h3><dl>${field('Helm',`${n(s.movement)} P`)}${field('Weapons',`${n(s.weapons)} P`)}${field('Flight deck',`${n(s.deck)} P`)}${field('Other / scanning',`${n(s.other)} P`)}</dl><p>Helm costs ${n(s.moveCost)} P/hex. A maneuver action does not fire; unused mounts can fire in a later hold.</p></section>
    <section class="power-node residual"><h3>04 / DEFEND</h3><strong>${n(s.remaining)} <small>P remaining</small></strong><p>${n(s.free)} P above reserve.</p><p>Incoming damage spends this same pool, limited by the struck face’s capacity and cost.</p></section>`;
  $('spec-equation').textContent=`${n(s.full)} supply − ${n(s.overhead)} upkeep/charge − ${n(s.movement)} helm − ${n(s.weapons)} weapons − ${n(s.deck)} deck − ${n(s.other)} other = ${n(s.remaining)} P remaining. Forecast only; incoming damage is not simulated.`;
  $('spec-shield-grid').innerHTML=s.shields.map(v=>`<div data-spec-shield="${v.face}"><span>${v.face} / ${esc(FACE_NAMES[v.face])}</span><strong>${n(v.absorbable)} damage affordable</strong><small>${n(v.capacity)} cap / action · ${n(v.cost)} P per damage</small><small>${esc(v.name)}</small></div>`).join('');
  $('spec-defense-note').textContent=`Each face above assumes it is struck next with the same ${n(s.remaining)} P. Do not add the six figures. Lower power/damage is more efficient. Intact face caps reset each action; the pool refills each turn. Unabsorbed damage reaches ${n(s.structure)} hull structure. Point defence ${n(s.pointDefence)} and screening ${n(s.screen)} are separate interception/screening ratings, not extra shield capacity.`;
  $('spec-battery').innerHTML=pack.design.mounts.map((m,i)=>{const v=weaponSpecification(pack,tuning,{mountId:m.id});return `<tr data-spec-row="${esc(m.id)}" ${m.id===selected?'class="selected-spec"':''}><td><button type="button" data-spec-mount="${esc(m.id)}" aria-pressed="${m.id===selected}">${String(i+1).padStart(2,'0')} / ${esc(v.name)}</button><small>${esc(v.family)} · ${esc(arcLabel(m.faces,tuning.arcs))}</small></td><td>${v.maxRange} hex</td><td>${v.kind==='beam'?'≤ ':''}${n(v.power)} P</td><td>${v.magazine===null?'None':`${v.magazine} shared / 1 per launch`}</td><td>${esc(v.cadence)}</td></tr>`;}).join('')||'<tr><td colspan="5">No weapons installed.</td></tr>';
  $('spec-weapon-detail').innerHTML=weaponDossier(w)+(w?.installation?`<p class="spec-note">${esc(w.installation.id)} · ${esc(arcLabel(w.installation.faces,tuning.arcs))} · X ${n(w.installation.position.x)}, Y ${n(w.installation.position.y)}, Z ${n(w.installation.position.z)}. Placement is physical metadata; coverage uses the exact face set at the ship hex.</p><h3>SELECTED MOUNT / CURRENT FORECAST</h3><div class="spec-action-grid">${f.actions.map(a=>{const shot=a.mounts.find(m=>m.mountId===selected);return `<div><span>Action ${a.round}</span><strong>${esc(shot?.reason||'Unavailable')}</strong><small>${shot?.eligible?`${n(shot.power)} P weapon draw · `:''}${n(a.power)} P ship pool after action</small></div>`;}).join('')}</div>`:'');
  $('spec-magazine').textContent=`Ship magazine: ${s.magazine} at start → ${s.magazineRemaining} after this forecast. All missile mounts draw from these same rounds.`;
  $('spec-caveat').textContent=f.caveat;
}
